// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using tbk_pos.infractructure.dto;
//
//    var transaccionDto = TransaccionDto.FromJson(jsonString);

namespace tbk_pos.infractructure.dto
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class TransaccionDto
    {
        [JsonProperty("Monto")]
        public long Monto { get; set; }

        [JsonProperty("Folio")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Folio { get; set; }

        [JsonProperty("Detalle")]
        public Detalle[] Detalle { get; set; }
    }

    public partial class Detalle
    {
        [JsonProperty("TEGiroId")]
        public long TeGiroId { get; set; }

        [JsonProperty("Folio")]
        public long Folio { get; set; }

        [JsonProperty("Identificacion")]
        public string Identificacion { get; set; }

        [JsonProperty("PAPersonaId")]
        public long PaPersonaId { get; set; }

        [JsonProperty("RutNumero")]
        public long RutNumero { get; set; }

        [JsonProperty("RutDigito")]
        public string RutDigito { get; set; }

        [JsonProperty("Nombres")]
        public string Nombres { get; set; }

        [JsonProperty("Direccion")]
        public string Direccion { get; set; }

        [JsonProperty("Monto")]
        public long Monto { get; set; }

        [JsonProperty("Reajuste")]
        public long Reajuste { get; set; }

        [JsonProperty("Intereses")]
        public long Intereses { get; set; }

        [JsonProperty("Total")]
        public long Total { get; set; }

        [JsonProperty("Glosa")]
        public string Glosa { get; set; }

        [JsonProperty("Boletin")]
        public string Boletin { get; set; }

        [JsonProperty("FechaVencimiento")]
        public string FechaVencimiento { get; set; }

        [JsonProperty("Pago")]
        public bool Pago { get; set; }

        [JsonProperty("CCosto")]
        public string CCosto { get; set; }
    }

    public partial class TransaccionDto
    {
        public static TransaccionDto FromJson(string json) => JsonConvert.DeserializeObject<TransaccionDto>(json, tbk_pos.infractructure.dto.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this TransaccionDto self) => JsonConvert.SerializeObject(self, tbk_pos.infractructure.dto.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
}
