// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using tbk_pos.infractructure.dto;
//
//    var ventaRequestDto = VentaRequestDto.FromJson(jsonString);

namespace tbk_pos.infractructure.dto
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class VentaRequestDto
    {
        [JsonProperty("Monto")]
        public int Monto { get; set; }

        [JsonProperty("Folio")]
        public int Folio { get; set; }
    }

    public partial class VentaRequestDto
    {
        public static VentaRequestDto FromJson(string json) => JsonConvert.DeserializeObject<VentaRequestDto>(json, tbk_pos.infractructure.dto.Converter.Settings);
    }

    public static class SerializeX
    {
        public static string ToJson(this VentaRequestDto self) => JsonConvert.SerializeObject(self, tbk_pos.infractructure.dto.Converter.Settings);
    }

    internal static class ConverterX
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
